package app.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import lombok.Getter;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class FriendDetailsView {
    @Getter
    private JPanel friendListPanel;
    @Getter
    private JButton backButton;
    private JLabel nicknameLabel;
    @Getter
    private JLabel nicknameValue;
    private JLabel noGamesLabel;
    @Getter
    private JLabel noGamesValue;
    private JLabel noFriendsLabel;
    private JLabel favoriteGameLabel;
    @Getter
    private JLabel favoriteGameValue;
    @Getter
    private JLabel noFriendsValue;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        friendListPanel = new JPanel();
        friendListPanel.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        friendListPanel.setBackground(new Color(-13395457));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-15118977));
        friendListPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Times New Roman", Font.BOLD, 20, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-1));
        label1.setText("Friend Details");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setIcon(new ImageIcon(getClass().getResource("/photos/GameGO_logo.png")));
        label2.setText("");
        panel1.add(label2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(5, 4, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-15118977));
        friendListPanel.add(panel2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        nicknameValue = new JLabel();
        Font nicknameValueFont = this.$$$getFont$$$("Times New Roman", -1, 20, nicknameValue.getFont());
        if (nicknameValueFont != null) nicknameValue.setFont(nicknameValueFont);
        nicknameValue.setForeground(new Color(-1));
        nicknameValue.setText("");
        panel2.add(nicknameValue, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        noGamesLabel = new JLabel();
        Font noGamesLabelFont = this.$$$getFont$$$("Times New Roman", -1, 20, noGamesLabel.getFont());
        if (noGamesLabelFont != null) noGamesLabel.setFont(noGamesLabelFont);
        noGamesLabel.setForeground(new Color(-1));
        noGamesLabel.setText("Number of Games:");
        panel2.add(noGamesLabel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        noGamesValue = new JLabel();
        Font noGamesValueFont = this.$$$getFont$$$("Times New Roman", -1, 20, noGamesValue.getFont());
        if (noGamesValueFont != null) noGamesValue.setFont(noGamesValueFont);
        noGamesValue.setForeground(new Color(-1));
        noGamesValue.setText("");
        panel2.add(noGamesValue, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        noFriendsLabel = new JLabel();
        Font noFriendsLabelFont = this.$$$getFont$$$("Times New Roman", -1, 20, noFriendsLabel.getFont());
        if (noFriendsLabelFont != null) noFriendsLabel.setFont(noFriendsLabelFont);
        noFriendsLabel.setForeground(new Color(-1));
        noFriendsLabel.setText("Number of Friends:");
        panel2.add(noFriendsLabel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        noFriendsValue = new JLabel();
        Font noFriendsValueFont = this.$$$getFont$$$("Times New Roman", -1, 20, noFriendsValue.getFont());
        if (noFriendsValueFont != null) noFriendsValue.setFont(noFriendsValueFont);
        noFriendsValue.setForeground(new Color(-1));
        noFriendsValue.setText("");
        panel2.add(noFriendsValue, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        favoriteGameLabel = new JLabel();
        Font favoriteGameLabelFont = this.$$$getFont$$$("Times New Roman", -1, 20, favoriteGameLabel.getFont());
        if (favoriteGameLabelFont != null) favoriteGameLabel.setFont(favoriteGameLabelFont);
        favoriteGameLabel.setForeground(new Color(-1));
        favoriteGameLabel.setText("Favorite Game:");
        panel2.add(favoriteGameLabel, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        favoriteGameValue = new JLabel();
        Font favoriteGameValueFont = this.$$$getFont$$$("Times New Roman", -1, 20, favoriteGameValue.getFont());
        if (favoriteGameValueFont != null) favoriteGameValue.setFont(favoriteGameValueFont);
        favoriteGameValue.setForeground(new Color(-1));
        favoriteGameValue.setText("");
        panel2.add(favoriteGameValue, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel2.add(spacer2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        backButton = new JButton();
        backButton.setText("Back");
        panel2.add(backButton, new GridConstraints(4, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nicknameLabel = new JLabel();
        nicknameLabel.setBackground(new Color(-1));
        Font nicknameLabelFont = this.$$$getFont$$$("Times New Roman", -1, 20, nicknameLabel.getFont());
        if (nicknameLabelFont != null) nicknameLabel.setFont(nicknameLabelFont);
        nicknameLabel.setForeground(new Color(-1));
        nicknameLabel.setText("Nickname:");
        panel2.add(nicknameLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        friendListPanel.add(spacer3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        friendListPanel.add(spacer4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return friendListPanel;
    }

}
